### ISSUE TITLE
Display results to the screen and ignoring tags

### ISSUE THREAD

**Issue by OttawaIan** [commercehub-oss/gradle-cucumber-jvm-plugin#26] opened 2016-09-08 17:11 UTC
Two questions:

How can i see the results of the cucumber tests to the screen when I call "gradle cucumberTest" ?  i.e. if I don't use the plugin I would see:

1 features completed.
    Scenarios [    3 completed,     3 failed]
        Steps [    9 completed,     4 failed,     5 skipped,     0 pending]

I want to give the user an indication of whether or not things worked or not without having to go to the reports directory.  

Also in the tags can I set it up so that I can ignore things that have a tag of @WIP, I know that you can say run tags via 
tags = ['@RUN_ME']

Thanks

Ian

**Comment by JayStGelais** [comment] 2016-09-08 17:18
Can you include what output you do get from the build?

**Comment by JayStGelais** [comment] 2016-09-08 17:23
@OttawaIan When I run tests with the plugin I see the output you are asking for. Perhaps you have your build misconfigured and aren't finding any tests. If you can post a public repo that demonstrates the behaviour you are seeing I could take a look.

As for ignoring tags, you could do something like this:
`tags = ['~@WIP']`

**Comment by OttawaIan** [comment] 2016-09-08 18:03
You are right on, it wasn't running my tests, and that ignore tags doesn't seem to be working if I had my gradle file with the cucumber task as included below.  It works when I comment out the tags, it didn't work if I specified it as:
tags = ['~@WIP', '@TestOne']

Any ideas ?

Thanks again 

cucumberTest {
    stepDefinitionRoots = ['classpath:cucumber/steps']
    //to only run a select number of tests
    tags = ['~@WIP']
    junitReport = true
    //if turned on it will fail for undefined or pending steps
    //isStrict = true
}

And my feature file looked like:
#Sample Feature Definition Template
Feature: Sample Feature file for project

  @TestOne
  Scenario: Open the test page
    Given I navigate to the web page
    When I click on the apply button
    Then The apply page has to be loaded correctly

  @WIP
  Scenario Outline: Title of your scenario outline
    Given I want to write a step with <name>
    When I check for the <value> in step
    Then I verify the <status> in step

    Examples:
      | name  | value | status  |
      | name1 |     5 | success |
      | name2 |     7 | Fail    |

**Comment by JayStGelais** [comment] 2016-09-08 18:17
@OttawaIan Try taking the 'classpath:' out of your stepDefinitionRoots specification. This plugin is always going to look on the classpath.

**Comment by OttawaIan** [comment] 2016-09-08 18:34
I tried that, and still the same problem arises, with the tags.  The not or equal tags neither or them seem to work, i remove it all together and wham things work. I am using 0.7 version of your plugin, with gradle 2.3

I am running ./gradlew clean cucumberTest


cucumberTest {
    stepDefinitionRoots = ['cucumber/steps']
    //to only run a select number of tests
    //tags = ['~@WIP']
    //tags = ['@Run']
    junitReport = true
    //if turned on it will fail for undefined or pending steps
    //isStrict = true
}


Thanks, 

Ian

**Comment by JayStGelais** [comment] 2016-09-08 18:40
@OttawaIan I don't think I'm going to figure this out from code snippets in the comments of this issue. Can you put up a public repo that demonstrates the issue. I'll pull it down and take a deeper look.

**Comment by OttawaIan** [comment] 2016-09-08 18:42
Sure let me see where I can put this, thanks again for the assistance

**Comment by OttawaIan** [comment] 2016-09-08 20:59
First time pushing something up - https://github.com/OttawaIan/GradleCucumberSample/tree/master/cukes-gradle-sample  

I run it now, i see no results even without tags being specified but the report (in reports dir) shows all the features being run.  Is there any other debugging I can do to figure out why the tests appear not to be run even though I get a report.  If I have an error in one of my step implementation then I was seeing the results displayed to the console.

Thanks again

**Comment by JayStGelais** [comment] 2016-09-09 15:27
I ran your build locally. The report is being generated and when I uncommented out the tags line (adding ~@WIP) it worked as expected.

I think I understand your concern now. That is that you don't get output to the console when the tests pass. That is expected behaviour. Similar to how the unit test tasks work in gradle. test and failure counts are only outputted to the console if there is at least one failure.

**Comment by OttawaIan** [comment] 2016-09-09 15:40
Ah okay thanks for the confirmation on that.  I didn't realize that - is there any way we can override this ? so that we get results if they pass or not.  The only reason I ask, is that this is the same behaviour if the person makes a mistake and we can't find any features to run.  Also I assume if we want to re-run the cucumber task again we should be using the --rerun-tasks on the command line ?

**Comment by JayStGelais** [comment] 2016-09-09 17:28
I think it might be a more useful option to have the ability to fail the test run if no features were run. Would that accomplish what you are looking for?

As for the --rerun-tasks flag, that would be necessary if you are running again without changing any source files.

**Comment by OttawaIan** [comment] 2016-09-14 19:26
Yes more feedback on some of the error cases would be awesome, or if there were no tests picked.  

I noticed the plugin doesn`t seem to work with gradle higher than 2.13. The error message I get appears to say that it got introduced in gradle 2.14.   Have you tried later versions of gradle ?

Thanks again

**Comment by OttawaIan** [comment] 2016-09-14 22:41
This is the error we see with gradle version greater than 2.13

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cucumberTest'.
> No service of type ProgressLoggerFactory available in ProjectScopeServices.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by JayStGelais** [comment] 2016-09-15 14:21
Thanks for this catch. I will look into this.

**Comment by OttawaIan** [comment] 2016-09-16 14:03
Is it possible to pass in parameters to my Java class that implements the Feature.  I noticed that if I added in

systemProperties System.getProperties()

When I add this to the cucumberTask no tests run.  Is there a reason why this wouldn't work, or is there another way to pass parameters into our tests ?  We are looking at passing in the host and port of the running Web Server

**Comment by JayStGelais** [comment] 2016-09-16 14:31
The systemProperties attribute on the CucumberTask expects a Map<String, String>. System.getProperties() returns a properties object, which implements Map<Object,Object>, so perhaps there is a class casting issue with that approach.

**Comment by OttawaIan** [comment] 2016-09-16 14:42
The stacktrace looks like:


:cucumberTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cucumberTest'.
> One or more feature files failed to parse. See error output above

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':cucumberTest'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)

The debug output looks like:

07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter]
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter]
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':cucumberTest'.
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter] > One or more feature files failed to parse. See error output above
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter]
07:36:17.799 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
07:36:17.800 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
07:36:17.800 [LIFECYCLE] [org.gradle.BuildResultLogger]
07:36:17.800 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
07:36:17.800 [LIFECYCLE] [org.gradle.BuildResultLogger]


So it appears like it can't find the feature files.  Is there another way I get the host and port ?  I thought of reading from a properties file in the short-term.   Your comment above I assume pertains the plugin code ?

**Comment by JayStGelais** [comment] 2016-09-16 15:24
I suspect the error "One or more feature files failed to parse." is unrelated to your attempts to pass system variables to the test. If all your are trying to do is pass a host and port, I would try something that looks like this:
`
testTaskName {
    ... // other configuration
    systemProperties = [
        host: 'http://myhost.com',
        port: '80'
    ]
}
`

* disclaimer: I have not attempted to complile and run code above. It may have minor syntax errors.

**Comment by JayStGelais** [comment] 2016-11-26 16:13
The issue with ProgressLoggerFactory has been fixed by Pull Request #28 . Scanning through this thread it seems that was the only concrete issue that needed to be fixed.

Closing this issue.

**Closed by JayStGelais** 2016-11-26 16:13 UTC
